# Generated by Django 5.1.6 on 2025-08-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_client_created_at_client_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Está excluido?')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
